### ISSUE TITLE
Make all contents included in _pages catchier and more professional

### ISSUE THREAD

**Issue by abuzarmahmood** [abuzarmahmood/abuzarmahmood.github.io#20]
See config/_navigation to see what pages are included

**Comment by abuzarmahmood** [comment]
The issue at hand involves making the contents included in the `_pages` directory of the repository "abuzarmahmood/abuzarmahmood.github.io" catchier and more professional. The focus is on enhancing the navigation elements, as indicated by the reference to `config/_navigation`.

### Suggestions and Changes Made:

1. **File Identified for Modification:**
   - **File:** `/home/exouser/Desktop/blech_github_bot/src/repos/abuzarmahmood/abuzarmahmood.github.io/_sass/_navigation.scss`
   - **Description:** This file contains the styling for navigation elements, including breadcrumb navigation, pagination, and various navigation lists. Enhancing the styles here can contribute to a more professional and visually appealing navigation experience.

2. **Plan to Address the Issues:**
   - Enhance the visual appeal of navigation elements by updating styles in `_sass/_navigation.scss`.
   - Ensure that the navigation elements are more engaging and professional by adjusting colors, fonts, and animations.

3. **Specific Changes Suggested:**

   - **Breadcrumb Navigation:**
     - **Line:** 8-50
     - **Description of Change:** Update the breadcrumb navigation to have a more modern look by adjusting font size, color, and adding subtle animations.
     - **Code Snippet:**
       ```scss
       .breadcrumbs {
         font-size: 1.1rem; // Increase font size for better readability
         color: $primary-color; // Use primary color for text
         text-transform: uppercase; // Make text uppercase for emphasis
         -webkit-animation: fadeIn 0.5s both; // Add fade-in animation
                 animation: fadeIn 0.5s both;
       }
       ```

   - **Pagination Navigation:**
     - **Line:** 58-157
     - **Description of Change:** Enhance pagination buttons with rounded corners and hover effects to make them more interactive.
     - **Code Snippet:**
       ```scss
       .pagination {
         li a {
           border-radius: 5px; // Add rounded corners
           transition: background-color 0.3s ease; // Smooth transition for hover effect
           &:hover {
             background-color: $secondary-color; // Change background on hover
           }
         }
       }
       ```

   - **Greedy Navigation:**
     - **Line:** 174-307
     - **Description of Change:** Improve the greedy navigation by adding a background gradient and enhancing button styles.
     - **Code Snippet:**
       ```scss
       .greedy-nav {
         background: linear-gradient(to right, $primary-color, $secondary-color); // Add gradient background
         button {
           border-radius: 5px; // Round button corners
           &:hover {
             background-color: darken($primary-color, 10%); // Darken button on hover
           }
         }
       }
       ```

These changes aim to make the navigation elements more visually appealing and professional, contributing to a better user experience on the website.

---
*This response was automatically generated by blech_bot using model gpt-4o*

---
*This response was automatically generated by blech_bot*
